### ISSUE TITLE
src/curl/curl.h is missing

### ISSUE THREAD

**Issue by rockmanbest** [aphenriques/quote#2]
Brilliant codes which are very illuminating, except that the part curl.h is missing. Sincerely wish you to publish the header or give us readers any clues on how the file is built up. Thx :)

**Comment by aphenriques** [comment]
Thanks for the compliment @rockmanbest ! curl.h is part of libcurl (https://curl.haxx.se/libcurl/) which is the library used by `quote` for URL transfer. You may dowload it from the link provided. There should be additional information on how to set it up for your system.
